version: '2'
services:
   web_pcam:
    hostname: web_demo_pcam
    image: richarvey/nginx-php-fpm:1.6.4
    environment:
      _DB_PASSWORD: ${DB_PASSWORD}
      _DB_NAME: ${DB_NAME}
      _DB_USER: ${DB_USER}
      _DB_HOST: ${DB_HOST}
      _DB_PORT: ${DB_PORT}
      _HOST_ID: ${HOST_ID}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${PATH_CODE}:/var/www/html
      - ${PATH_CODE}/.docker/nginx/sites-available:/etc/nginx/sites-enabled:ro
      - ${PATH_CODE}/.docker/nginx/ssl:/etc/nginx/ssl
      - ${PATH_CODE}/.docker/nginx/log/access.log:/var/log/nginx/access.log 
      - ${PATH_CODE}/.docker/nginx/log/error.log:/var/log/nginx/error.log
      #- ${PATH_CODE}/.docker/nginx/php:/usr/local/etc/php

