version: '2'
services:
   web_pcam:
    hostname: web_pcam
    image: richarvey/nginx-php-fpm:1.6.4
    environment:
      _DB_PASSWORD: ${DB_PASSWORD}
      _DB_NAME: ${DB_NAME}
      _DB_USER: ${DB_USER}
      _DB_HOST: ${DB_HOST}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${PATH_CODE}:/var/www/html
      - ${PATH_CODE}/.docker/nginx/sites-available:/etc/nginx/sites-enabled:ro
